model:
  base_learning_rate: 5.0e-07
  target: ldm.models.diffusion.ddpm_tactile_nerf.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: aux
    image_size: 32
    channels: 4
    cond_stage_trainable: true
    concat_mode: true
    scale_by_std: true
    monitor: val/loss_simple_ema
    ignore_keys: []
    ckpt_path: pretrained_models/img2touch.ckpt

    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps:
        - 10
        cycle_lengths:
        - 10000000000000
        f_start:
        - 1.0e-06
        f_max:
        - 1.0
        f_min:
        - 1.0
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 68
        out_channels: 4
        model_channels: 192
        attention_resolutions:
        - 1
        - 2
        - 4
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 2
        - 4
        - 4
        num_heads: 8
        use_scale_shift_norm: true
        resblock_updown: true
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ckpt_path: models/first_stage_models/kl-f8/model.ckpt
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.ResnetRGBDEncoder

      params:
        # model_name: resnet18
        model_name: resnet50

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 48
    num_workers: 8
    wrap: false
    train:
      target: ldm.data.tactile_nerf.TouchTrain
      params:
        size: 256
        main_modality: touch
        transform_flag: True
        rgb_flag: True
        depth_flag: True
        scale_list: ['40_30']
    validation:
      target: ldm.data.tactile_nerf.TouchValidation
      params:
        size: 256
        main_modality: touch
        transform_flag: False
        rgb_flag: True
        depth_flag: True
        scale_list: ['40_30']
    test:
      target: ldm.data.tactile_nerf.TouchTest
      params:
        size: 256
        main_modality: touch
        transform_flag: False
        rgb_flag: True
        depth_flag: True
        scale_list: ['40_30']

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 200
        max_images: 8
        increase_log_steps: False


  trainer:
    benchmark: True
    max_epochs: 300